### ISSUE TITLE
RuntimeError: istft input and window must be on the same device but got self on cuda:0 and window on cpu

### ISSUE THREAD

**Issue by egorsmkv** [rishikksh20/iSTFTNet-pytorch#14]
My command to run:

```
python3 train.py --config config_v1.json --input_wavs_dir /home/yehor/iSTFTNet-pytorch/lada_wavs --input_training_file /home/yehor/iSTFTNet-pytorch/training_list.txt --input_validation_file /home/yehor/iSTFTNet-pytorch/validation_list.txt
```

Error: 
```
...        (2): Conv1d(128, 128, kernel_size=(11,), stride=(1,), padding=(5,))
      )
    )
  )
  (conv_post): Conv1d(128, 18, kernel_size=(7,), stride=(1,), padding=(3,))
  (reflection_pad): ReflectionPad1d((1, 0))
)
checkpoints directory :  cp_hifigan
Epoch: 1
/home/yehor/.local/lib/python3.8/site-packages/torch/functional.py:632: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:801.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/yehor/.local/lib/python3.8/site-packages/torch/functional.py:632: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:801.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/yehor/.local/lib/python3.8/site-packages/torch/functional.py:632: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:801.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/yehor/.local/lib/python3.8/site-packages/torch/functional.py:632: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:801.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    main()
  File "train.py", line 276, in main
    train(0, a, h)
  File "train.py", line 126, in train
    y_g_hat = stft.inverse(spec, phase)
  File "/home/yehor/iSTFTNet-pytorch/stft.py", line 198, in inverse
    inverse_transform = torch.istft(
RuntimeError: istft input and window must be on the same device but got self on cuda:0 and window on cpu
```

**Comment by egorsmkv** [comment]
It seems that @johnpaulbin fixed this issue in own fork https://github.com/johnpaulbin/iSTFTNet-pytorch

**Comment by egorsmkv** [comment]
The same problem is in inference.py too

**Comment by a897456** [comment]
> It seems that @johnpaulbin fixed this issue in own fork https://github.com/johnpaulbin/iSTFTNet-pytorch

https://github.com/johnpaulbin/iSTFTNet-pytorch/blob/2ae293919b8544989e93d3cc4a58e2f5a07e9388/stft.py#L201
add"to(self.device)"  
But how does the blogger run the program?

**Comment by Ashigarg123** [comment]
In train.py add this line :  stft.window = stft.window.to(spec.device)
                                         y_g_hat = stft.inverse(spec, phase)
